apiVersion: v1
kind: Service
metadata:
  name: demo-service-external
  labels:
    app: demo-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:741570836596:certificate/3f27fafc-02e8-49f3-87af-fac0b62b7bf2
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http" # tcp
    service.beta.kubernetes.io/aws-load-balancer-name: demo
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    external-dns.alpha.kubernetes.io/hostname: demo.rayhshtat.com
    external-dns.alpha.kubernetes.io/ttl: "60"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: demo-service
