apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- external-service.yaml
- hpa.yaml
- pdb.yaml

namespace: demo

commonLabels:
  app.kubernetes.io/name: demo-service
  app.kubernetes.io/part-of: demo-platform
images:
- name: 741570836596.dkr.ecr.eu-central-1.amazonaws.com/ecr-lab-demo
  newTag: v1.1
